### ISSUE TITLE
how can i create groupchats on signal? 

### ISSUE THREAD

**Issue by Happyfeet01** [mautrix/signal#172]
Hello, 

How can i create an Groupchats with other signalusers? I can't find  any command for that.

**Comment by Lykos153** [comment]
I just ran into the same issue. Here's what I tried:

1. Create  new room and invite two signal ghosts. They leave immediately with "This ghost does not join multi-user rooms without the bridge bot."
2. Create new room, invite bridge bot, make it admin and then invite two signal ghosts. Now they stay, but the bridge replies with "This is not a portal room." when I try to run eg `!signal set-relay`

I can join existing groups if I'm invited. But this is a problem, since all our users have the bridge as their primary device, so nobody is able to create a group

**Comment by maltee1** [comment]
The `create` command just entered master a few days ago, so if you need to be able to create groups, you can upgrade your bridge to the latest master. Or simply get a signal user to create the group and invite you

Inviting puppets can currently only create DMs, group creation on puppet invite is something I'm currently trying to implement, but I didn't get very far yet...

**Comment by maltee1** [comment]
I suppose this is fixed, maybe close?

**Comment by Happyfeet01** [comment]
Yes can be closed
