### ISSUE TITLE
Left DM rooms rebridge on next contact sync

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/signal#189]
After a period of time, or after startup users are seeing DM rooms they have left get re-bridged which is quite annoying for them.

**Comment by mulles** [comment]
Work around, ask the admin of the signal group or DM to kick you out of the room.

**Comment by maltee1** [comment]
Signald doesn't seem to have a way to delete a user. You can set `autocreate_contact_portal` to false to prevent contact portals from popping up by themselves, but that might be desired behavior in other situations.
Otherwise mautrix-signal would have to keep a list of contacts that are in signald but that users left the portal of. I don't think that's a good idea.
Or you can file an issue with signald to allow deleting contacts.
