### ISSUE TITLE
You are not whitelisted to use this bridge error

### ISSUE THREAD

**Issue by jeena** [mautrix/signal#298]
I already have one user using the bridge without problems. I tried to invite the bot to another user but despite me adding the whole domain to the whitelist like this:

```
bridge:
    permissions:
        '@jeena:jeena.net': admin
        'jeena.net': user
```
I'm getting this error:

```
You are not whitelisted to use this bridge.

If you are the owner of this bridge, see the bridge.permissions section in your config file.
Signal bridge bot left, was invited and joined
```
I restarted the bridge and the synapse server and then in my desperation rebooted my server but it doesn't change anything.

**Comment by MayeulC** [comment]
Can we have more details as to what's happening there? A user reported encountering the same issue.

**Comment by tulir** [comment]
The error message is really all there is to it. If it happens even when you think you configured it correctly, it just means you didn't actually configure it correctly. In this case, the problem was editing a copy of the config instead of the real config (the bridge obviously can't solve such issues).

**Comment by MayeulC** [comment]
Thank you for clarifying; this lead the user to think multi-user bridging was unsupported, and they broke a lot of assumptions on the yunohost end by trying to install two bridges instances with the same synapse server.

Turns out their configuration was broken too, using `domain` instead of `actual.example.com` as the domain name.
