### ISSUE TITLE
Bridging to an existing Matrix room breaks the `_locked_confirm_bridge` function

### ISSUE THREAD

**Issue by ketsapiwiq** [mautrix/signal#329]
On [mautrix-signal](https://github.com/mautrix/signal) [0.4.2](https://github.com/mautrix/signal/releases/tag/v0.4.2):

Hadrien:
> `bridge SIGNAL_ID MATRIX_ID`

Signal bridge bot:
> That Signal chat has no existing portal. To confirm bridging the chat to this room, use 
continue

Hadrien:
> continue

Signal bridge bot:
> Unhandled error while handling command:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 495, in confirm_bridge
    await _locked_confirm_bridge(
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 521, in _locked_confirm_bridge
    (
ValueError: too many values to unpack (expected 5)
```

After this, the bridging still works **but messages bridged from Signal are all unsigned** (even though the Signal bot can correctly read the encrypted Signal commands sent through this room).

The bridge does appear in Active Portal Rooms when typing `clean-rooms`.
![image](https://user-images.githubusercontent.com/26697460/205791847-2ce5b2f3-fc48-4848-8b77-74a0f8575e71.png)

If I let the bridge create the Matrix room instead of an existing one, end-to-bridge encryption is fully working.

My config is:
```
    encryption:
        allow: true
        default: true
        appservice: false
        require: true
        allow_key_sharing: true
```

The problem is the same if using `unbridge-and-continue`, `delete-and-continue`, or manually unbridge then use `bridge` from a private chat or the room.

I have already tried resetting the mautrix-signal postgres db once.

PS: while googling, found this comment in this other issue on an older version https://github.com/mautrix/signal/issues/316#issue-1428197242

**Comment by ketsapiwiq** [comment]
Line 521 is the third one:
```py
    portal.mxid = room_id
    portal.by_mxid[portal.mxid] = portal
    (
        portal.title,
        portal.about,
        levels,
        portal.encrypted,
        portal.photo_id,
    ) = await get_initial_state(evt.az.intent, evt.room_id)
    await portal.save()
    await portal.update_bridge_info()
```
So I suspect the room's encryption state gets bugged in the process.

Thanks!

**Comment by alarig** [comment]
Here I had to add the user running the bridge to the group running `signald`

**Comment by ketsapiwiq** [comment]
Everything is owned by root there:
```bash
hadrien@tomate:~/matrix(main⚡) » docker exec signald id        
uid=0(root) gid=0(root) groups=0(root)
hadrien@tomate:~/matrix(main⚡) » docker exec mautrix-signal id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
hadrien@tomate:~/matrix(main⚡) » docker exec synapse id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by maxmati** [comment]
I have the same issue.

It seems to be related to this commit https://github.com/mautrix/signal/commit/247aed54ee735a291c5f96d8e7c87fa0a50dc291

It added join_rules to get_initial_state but missed it's usage in _locked_confirm_bridge. Although it was already fixed 3 months ago in https://github.com/mautrix/signal/commit/247aed54ee735a291c5f96d8e7c87fa0a50dc291but there was no release since this time.

**Comment by ketsapiwiq** [comment]
Thank you so much for your answer @maxmati!!!
I believe the second commit you're referring to is this one? https://github.com/mautrix/signal/commit/2cd84f4f4ac0a4af18aaf9ef814373ffb5405a75
Let's hope for a new release soon, I'll test with a rebuilt docker image if I have some time :)

**Comment by gitayam** [comment]
same exact issue . 


Steps to Reproduce:
1. Bridge a Signal chat room.
2. Attempt to bridge the same Signal chat room using the options to delete the portal completely and continue bridging.

Expected Behavior:
The Signal chat room should be successfully bridged without encountering any errors.

Actual Behavior:
An unhandled error occurs with the traceback indicating a "ValueError: too many values to unpack (expected 5)".

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 495, in confirm_bridge
    await _locked_confirm_bridge(
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 521, in _locked_confirm_bridge
    (
ValueError: too many values to unpack (expected 5)

```

Additional Information:
- This issue occurs specifically when using the delete-and-continue option to clean up a previously bridged Signal chat room.
- The error is observed in the `mautrix_signal` module.

Environment:
- Matrix-Docker-Ansible-Deploy version: master
- Operating System: Debian 5.10.178-3

Please let me know if you need any further information. Thank you!
