### ISSUE TITLE
FR: add a command to clean/delete all data related to existing login

### ISSUE THREAD

**Issue by 0spinboson** [mautrix/signal#389]
This request relates to https://github.com/mautrix/signal/issues/290 which affects me.

I would like to have an easy way to ask the bot to thoroughly clean all data pertaining to an existing login/device link, so I can use my existing matrix installation again for signal. 

Thank you!

**Comment by tulir** [comment]
The bridge does not use signald anymore, so that issue doesn't exist anymore, nor do any other signald-related issues.

**Comment by 0spinboson** [comment]
I'm sorry, but I don't follow. What does signald have to do with this? 

I am running a matrix instance that was last updated last month, and had an issue with my phone breaking so I had to activate signal on a new phone with no ability to restore history or whatever. I didn't unlink matrix because I had no idea this might be an issue. Since then I am getting exactly the same error as described.

**Comment by tulir** [comment]
The bridge previously used signald to connect to Signal. It had some bugs, like sometimes failing when trying to relink.

The main branch of the bridge does not use signald anymore, so those bugs don't exist anymore. Also, linking new devices on the old bridge is completely broken, because Signal changed their API and signald hasn't been updated yet.
